// <auto-generated />
using Business360.sso.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Business360.sso.Data.Migrations.APPDb
{
    [DbContext(typeof(APPDbContext))]
    [Migration("20191210163011_resource")]
    partial class resource
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Business360.sso.Data.Entities.ApiResource", b =>
                {
                    b.Property<string>("ApiResourceName")
                        .HasColumnType("text");

                    b.Property<string>("ApiResourceData")
                        .HasColumnType("text");

                    b.HasKey("ApiResourceName");

                    b.ToTable("ApiResources");
                });

            modelBuilder.Entity("Business360.sso.Data.Entities.IdentityResource", b =>
                {
                    b.Property<string>("IdentityResourceName")
                        .HasColumnType("text");

                    b.Property<string>("IdentityResourceData")
                        .HasColumnType("text");

                    b.HasKey("IdentityResourceName");

                    b.ToTable("IdentityResources");
                });

            modelBuilder.Entity("Business360.sso.Data.Entities.SsoClient", b =>
                {
                    b.Property<string>("ClientId")
                        .HasColumnType("text");

                    b.Property<string>("ClientData")
                        .HasColumnType("text");

                    b.HasKey("ClientId");

                    b.ToTable("Clients");
                });
#pragma warning restore 612, 618
        }
    }
}
